cygSqlite/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *

urlpatterns = [
    path('123456_admin123456/', admin.site.urls),
    path('',index,name="index"),
    path('role/',role,name="role"),
    path('user/', include('user.urls')),
    path('role_api/',role_api,name='role_api'),
]

user/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login_for_medal/', views.login_for_medal, name='login_for_medal'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('user_info/', views.user_info, name='user_info'),
    path('change_nickname/',views.change_nickname, name='change_nickname'),
    path('change_statement/',views.change_statement, name='change_statement'),
]

role/models.py
from django.db import models

# Create your models here.
class Role(models.Model):
    if30 = models.IntegerField(verbose_name='三十附体',default=0)
    star8 = models.IntegerField(verbose_name='8，9星装备数量，最高为16',default=0)
    price = models.IntegerField(verbose_name='价格')
    name = models.CharField(verbose_name='角色名', max_length=30)
    menpai = models.CharField(verbose_name='门派',max_length=20)
    cloth_grade = models.IntegerField(verbose_name='装备评分')
    stone_grade = models.IntegerField(verbose_name='宝石评分')
    level = models.IntegerField(verbose_name='等级')
    hp = models.IntegerField(verbose_name='血上限')
    tili = models.IntegerField(verbose_name='体力', default=0)
    shenfa = models.IntegerField(verbose_name='身法', default=0)
    attack_all_value = models.IntegerField(verbose_name='总属性攻击值', default=0)
    attack_heightest_name = models.CharField(verbose_name='最高属性攻击名称', max_length=30)
    attack_heightest_value = models.IntegerField(verbose_name='最高属性攻击值')
    others_attack = models.IntegerField(verbose_name='副属性攻击')
    attack_stab = models.IntegerField(verbose_name='穿刺攻击')
    huixin = models.IntegerField(verbose_name='会心')
    mingzhong = models.IntegerField(verbose_name='命中')
    shanbi = models.IntegerField(verbose_name='闪避')
    detail_url = models.CharField(verbose_name='详情链接', max_length=100)
    tili_d = models.IntegerField(verbose_name='体力鼎',default=0)
    shuxing_d = models.IntegerField(verbose_name='属性鼎',default=0)
    wuhun = models.IntegerField(verbose_name="武魂",default=0)
    if20 = models.IntegerField(verbose_name="双十珍兽",default=0)
    cailiao_3 = models.IntegerField(verbose_name="三级材料",default=0)
    shizhuang_num = models.IntegerField(verbose_name="时装数量",default=0)

    area = models.CharField(verbose_name="区服", max_length=200, default='')
    shenqi_star = models.IntegerField(verbose_name="神器星级",default=0)
    neiwai_max_attack = models.IntegerField(verbose_name="最高内外功",default=0)
    orange_zhenyuan = models.IntegerField(verbose_name='橙色金色真元数量',default=0)
    diaowen8 = models.IntegerField(verbose_name='8级雕文数量',default=0)
    diaowen7 = models.IntegerField(verbose_name='7级雕文数量',default=0)
    diaowen6 = models.IntegerField(verbose_name='6级雕文数量',default=0)
    yuanbao = models.IntegerField(verbose_name='所有元宝',default=0)
    kang_heightest_name = models.CharField(verbose_name="最高抗性名称",max_length=30,default="")
    kang_heightest_value = models.IntegerField(verbose_name="最高抗性值",default=0)
    zuoji = models.CharField(verbose_name="稀有坐骑",max_length=200,default='')
    nb_xinjue_num = models.IntegerField(verbose_name='稀有心决数量',default=0)

    chonglou_num = models.IntegerField(verbose_name="重楼个数",default=0)
    nb_animal_num = models.IntegerField(verbose_name="强力珍兽数量",default=0)
    shizhuang_name = models.CharField(verbose_name="时装颜色",max_length=10000, default='')
    zuoji_num = models.IntegerField(verbose_name="稀有坐骑数量", default=0)
    nb_xinjue_name = models.CharField(verbose_name="稀有心决名称",max_length=10000, default='')
    yigudan = models.IntegerField(verbose_name='移骨丹',default=0)




class visitNums(models.Model):
    name = models.CharField(verbose_name="名称",default="",max_length=50)
    visitnumsAll = models.IntegerField(verbose_name="总访问次数",default=0)

cygSqlite/forms.py
from django import forms


class SelectForm(forms.Form):
    SELVALUE = (
        ('全部门派', '全部'),
        ('少林', '少林'),
        ('明教', '明教'),
        ('丐帮', '丐帮'),
        ('武当', '武当'),
        ('峨嵋', '峨嵋'),
        ('星宿', '星宿'),
        ('天龙', '天龙'),
        ('天山', '天山'),
        ('逍遥', '逍遥'),
        ('慕容', '慕容'),
        ('唐门', '唐门'),
        ('鬼谷', '鬼谷'),
        ('桃花岛', '桃花岛'),
    )
    SELVALUE2 = (
        ('无等级限制','80-119'),
        ('80-89','80-89'),
        ('90-99','90-99'),
        ('100-119','100-119'),
    )

    SELVALUE3 = (
        ("无区服限制","无区服限制"),
        ("鸿运大区", "鸿运大区"),
        ("华中电信一区", "华中电信一区"),
        ("电信全国一区", "电信全国一区"),
        ("西南电信一区", "西南电信一区"),
        ("南部电信二区", "南部电信二区"),
        ("纵横双线", "纵横双线"),
        ("网通二区", "网通二区"),
        ("东北网通一区", "东北网通一区"),
        ("华东电信一区", "华东电信一区"),
        ("华东电信二区", "华东电信二区"),
        ("周年庆专区", "周年庆专区"),
        ("超级双线", "超级双线"),
        ("网通专区", "网通专区"),
        ("东部电信二区", "东部电信二区"),
        ("老友专区", "老友专区"),
        ("华北网通一区", "华北网通一区"),
        ("至尊电信", "至尊电信"),
        ("唯美双线", "唯美双线"),
        ("东部电信", "东部电信"),
        ("唯美电信", "唯美电信"),
        ("无双网通", "无双网通"),
        ("人气专区", "人气专区"),
    )
    SELVALUE4 = (
        ("无主属性限制", "无主属性限制"),
        ("冰属性", "冰属性"),
        ("火属性", "火属性"),
        ("玄属性", "玄属性"),
        ("毒属性", "毒属性")
    )
    lowPrice = forms.CharField(required=False)
    heightPrice = forms.CharField(required=False)
    baoshiLevel = forms.CharField(required=False)
    zhenyuanNum = forms.CharField(required=False)
    attack_heightest_value = forms.CharField(required=False)
    shizhuang_name = forms.CharField(required=False)
    nb_xinjue_name = forms.CharField(required=False)
    chonglou_num = forms.CharField(required=False)
    tili_d = forms.CharField(required=False)
    shuxing_d = forms.CharField(required=False)
    yigudan = forms.CharField(required=False)
    kang_heightest_value = forms.CharField(required=False)
    sel_value = forms.CharField(max_length=10, widget=forms.widgets.Select(choices=SELVALUE))
    sel_value2 = forms.CharField(max_length=10, widget=forms.widgets.Select(choices=SELVALUE2))
    sel_value3 = forms.CharField(max_length=15, widget=forms.widgets.Select(choices=SELVALUE3))
    sel_value4 = forms.CharField(max_length=15, widget=forms.widgets.Select(choices=SELVALUE4))

role/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block header_extends %}{% endblock %}
</head>
<body style="margin-top: 70px!important;">
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'index' %}">角色检索网站</a>
            <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar-collapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="{% block nav_home_active %}{% endblock %}">
                    <a href="{% url 'index' %}">首页</a>
                </li>
                <li class="{% block nav_role_active %}{% endblock %}">
                    <a href="{% url 'role' %}">角色检索</a>
                </li>
                <li>
                    <a href="http://39.105.61.245:8080/">作者的博客</a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if not user.is_authenticated %}

                <li>
                    <a href="{% url 'login' %}?from={{ request.get_full_path }}">登录</a>
                </li>
                <li>
                    <a href="{% url 'register' %}?from={{ request.get_full_path }}">注册</a>
                </li>
                {% else %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">{{ user.username }} <span
                            class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'user_info' %}">个人资料</a></li>
                        <li><a href="{% url 'logout' %}?from={{ request.get_full_path }}">退出</a></li>

                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

{% block content %}{% endblock %}
{% block script_extends %}{% endblock %}
</body>
</html>

templates/form.html
{% extends 'base.html' %}

{% block title %}{{ page_title }}{% endblock %}
{% block nav_home_active %}active{% endblock %}
{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ form_title }}</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                {% if not field.is_hidden %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% endif %}
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span class="pull-left text-danger">{{ form.non_field_errors }}</span>
                            <input type="submit" value={{submit_value}} class="btn btn-primary pull-right">
                        </form>
                    </div>
                </div>                
            </div>
        </div>
    </div>    
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    角色检索
{% endblock %}

{% block header_extends %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <h3 class="home-content">欢迎访问</h3>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}我的网站|登录{% endblock %}
{% block nav_home_active %}active{% endblock %}
{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">登录</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in login_form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span class="pull-left text-danger">{{ login_form.non_field_errors }}</span>
                            <input type="submit" value="登录" class="btn btn-primary pull-right">
                        </form>
                    </div>
                </div>                
            </div>
        </div>
    </div>    
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}我的网站|注册{% endblock %}
{% block nav_home_active %}active{% endblock %}
{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">注册</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in reg_form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span class="pull-left text-danger">{{ reg_form.non_field_errors }}</span>
                            <input type="submit" value="注册" class="btn btn-primary pull-right">
                        </form>
                    </div>
                </div>                
            </div>
        </div>
    </div>    
{% endblock %}

templates/role.html
{% extends 'base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
{% block title %}
角色检索
{% endblock %}
{% block header_extends %}
{% endblock %}


{% block nav_role_active %}active{% endblock %}

{% block content %}

<table class="table table-striped">
    <form action="" method="get">
        <div class="fieldWrapper" style="margin-top:80px">
            <label for="id_lowPrice">价格区间</label>
            {{select_form.lowPrice}}
            <lable>——</lable>
            <label for="id_heightPrice"></label>
            {{select_form.heightPrice}}
        </div>
        <select name="sel_value">
            {% for key,value in select_form.SELVALUE %}
            <option value="{{ value }}">{{ key }}</option>
            {% endfor %}
        </select>
        <lable>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</lable>
        <select name="sel_value2">
            {% for key,value in select_form.SELVALUE2 %}
            <option value="{{ value }}">{{ key }}</option>
            {% endfor %}
        </select>
        <lable>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</lable>
        <select name="sel_value3">
            {% for key,value in select_form.SELVALUE3 %}
            <option value="{{ value }}">{{ key }}</option>
            {% endfor %}
        </select>
        <lable>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</lable>
        <select name="sel_value4">
            {% for key,value in select_form.SELVALUE4 %}
            <option value="{{ value }}">{{ key }}</option>
            {% endfor %}
        </select>
        <div>
            <label for="id_baoshiLevel">宝石评分</label>
            {{select_form.baoshiLevel}}
            <label for="id_zhenyuanNum">橙色真元</label>
            {{select_form.zhenyuanNum}}
            <label for="id_tili_d">体力鼎</label>
            {{select_form.tili_d}}
            <label for="id_shuxing_d">属性鼎</label>
            {{select_form.shuxing_d}}
            <label for="id_attack_heightest_value">主属性攻击值</label>
            {{select_form.attack_heightest_value}}
            <label for="id_attack_shizhuang_name">时装颜色</label>
            {{select_form.shizhuang_name}}
            <label for="id_attack_nb_xinjue_name">秘技名称</label>
            {{select_form.nb_xinjue_name}}
            <label for="id_chonglou_num">重楼数量</label>
            {{select_form.chonglou_num}}
            <label for="id_kang_heightest_value">最高抗性</label>
            {{select_form.kang_heightest_value}}
            <label for="id_yigudan">移骨丹</label>
            {{select_form.yigudan}}
        </div>

        <input type="submit">
    </form>
    <div>小窍门：点击属性字段名称可以实现从高到低排序</div>
    <thead>
    <tr>
        {% for verbose_name in verbose_names %}
        <th>
            {% if request_url_all == '/role/' %}
            <a href="{{ request_url_all }}?verbose_name={{verbose_name}}">{{verbose_name}}</a>
            {% else %}
            <a href="{{ request_url_all }}&verbose_name={{verbose_name}}">{{verbose_name}}</a>
            {% endif %}
        </th>
        {% empty %}
        没有字段
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for role in roles %}
    <tr>
        <td>{{role.if30}}</td>
        <td>{{ role.star8 }}</td>
        <td>{{role.price}}</td>
        <td>{{role.name}}</td>
        <td>{{role.menpai}}</td>
        <td>{{role.cloth_grade}}</td>
        <td>{{role.stone_grade}}</td>
        <td>{{role.level}}</td>
        <td>{{role.hp}}</td>
        <td>{{role.tili}}</td>
        <td>{{role.shenfa}}</td>
        <td>{{role.attack_all_value}}</td>
        <td>{{role.attack_heightest_name}}</td>
        <td>{{role.attack_heightest_value}}</td>
        <td>{{role.others_attack}}</td>
        <td>{{role.attack_stab}}</td>
        <td>{{role.huixin}}</td>
        <td>{{role.mingzhong}}</td>
        <td>{{role.shanbi}}</td>
        <td><a href="{{role.detail_url}}" target="view_window">链接</a></td>
        <td>{{role.tili_d}}</td>
        <td>{{role.shuxing_d}}</td>
        <td>{{role.wuhun}}</td>
        <td>{{role.if20}}</td>
        <td>{{role.cailiao_3}}</td>
        <td>{{role.shizhuang_num}}</td>
        <td>{{role.area}}</td>
        <td>{{role.shenqi_star}}</td>
        <td>{{role.neiwai_max_attack}}</td>
        <td>{{role.orange_zhenyuan}}</td>
        <td>{{role.diaowen8}}</td>
        <td>{{role.diaowen7}}</td>
        <td>{{role.diaowen6}}</td>
        <td>{{role.yuanbao}}</td>
        <td>{{role.kang_heightest_name}}</td>
        <td>{{role.kang_heightest_value}}</td>
        <td>{{role.zuoji}}</td>
        <td>{{role.nb_xinjue_num}}</td>
        <td>{{role.chonglou_num}}</td>
        <td>{{role.nb_animal_num}}</td>

    </tr>
    {% empty %}

    {% endfor %}
    </tbody>
</table>

<div class="paginator">
    <ul class="pagination">
        {# 上一页 #}
        <li>
            {% if page_of_roles.has_previous %}
            <a href="?page={{ page_of_roles.previous_page_number }}&{{ request_url }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
            {% else %}
            <span aria-hidden="true">&laquo;</span>
            {% endif %}
        </li>
        {# 全部页码 #}
        {% for page_num in page_range %}
        {% if page_num == page_of_roles.number %}
        <li class="active"><span>{{ page_num }}</span></li>
        {% else %}
        {% if page_num == '...' %}
        <li><span>{{ page_num }}</span></li>
        {% else %}
        <li><a href="?page={{ page_num }}&{{ request_url }}">{{ page_num }}</a></li>
        {% endif %}
        {% endif %}
        {% endfor %}
        {# 下一页 #}
        <li>
            {% if page_of_roles.has_next %}
            <a href="?page={{ page_of_roles.next_page_number }}&{{ request_url }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
            {% else %}
            <span aria-hidden="true">&raquo;</span>
            {% endif %}
        </li>
    </ul>
    <p>
        共有{{ page_of_roles.paginator.count }}条角色信息，
        当前第{{ page_of_roles.number }}页，共{{ page_of_roles.paginator.num_pages }}页
    </p>
</div>
<div style="text-align: center;">网站总访问次数:{{ visitnum }}</div>
<div style="text-align: center;">想增加搜索字段，或者增加搜索内容可以联系微信：lzz122zzl</div>

{% endblock %}

templates/user_info.html
{% extends 'base.html' %}

{% block title %}个人资料{% endblock %}
{% block nav_home_active %}active{% endblock %}
{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                {% if user.is_authenticated %}
                    <h2>{{ user.username }}</h2>
                    <ul>
                        <li>昵称：{{ user.profile.nickname }} <a href="{% url 'change_nickname' %}">修改昵称</a></li>
                        <li>邮箱：{% if user.email %}{{ user.email }}{% else %}未绑定 <a href="#">绑定邮箱</a>{% endif %}</li>
                        <li>上一次登录的时间：{{ user.last_login|date:"Y-m-d H:i:s" }}</li>
                        <li>个人简介：{{ user.profile.statement }} <a href="{% url 'change_statement' %}">修改个人简介</a></li>
                        <li><a href="#">修改密码</a></li>
                    </ul>
                {% else %}
                    <span>未登录，跳转到首页...</span>
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}